<a href="https://colab.research.google.com/github/PraveenPrabhat125/NLP_sentiment_analysis/blob/main/Sentiment_using_bert_NLP.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# 1. Install and Import Dependencies

In [ ]:
!pip install torch torchvision torchaudio --index-url https://download.pytorch.org/whl/cu121

Looking in indexes: https://download.pytorch.org/whl/cu121


5 library transformers requests beautifulsoup4 pandas numpy
1. transformers : is used for the importing NLP model
2. request : for scraping test form website
3. beautifulsoup4 : Python library for pulling data out of HTML and XML files.
4. NumPy: A Python library for numerical operations, providing efficient array processing and mathematical functions for scientific computing.

5. Pandas: Built on NumPy, it offers high-level data structures like Series and DataFrame, designed for easy and efficient data manipulation and analysis in Python.


In [ ]:
!pip install transformers requests beautifulsoup4 pandas numpy

**AutoTokenizer**: Automatically loads a tokenizer for a pre-trained NLP model based on the specified model name or path.

**AutoModelForSequenceClassification**: Automatically loads a pre-trained NLP model for sequence classification based on the specified model name or path. It's commonly used for tasks like sentiment analysis or text classification.

In simpler terms, these classes help you easily use powerful pre-trained language models for tasks like understanding and classifying sequences of text without needing to handle the details of model loading and tokenization manually.

**re Module**: Python module for working with regular expressions, powerful patterns used for matching and manipulating text.

In [ ]:
from transformers import AutoTokenizer, AutoModelForSequenceClassification
import torch
import requests
from bs4 import BeautifulSoup
import re

# 2. Instantiate Model


**Hugging Face** is a company and an open-source community that focuses on natural language processing (NLP) and provides a platform for sharing and utilizing pre-trained models.

we have imported ## bert-base-multilingual-uncased model ##

# Note:
This is a bert-base-multilingual-uncased model finetuned for sentiment analysis on product reviews in six languages: English, Dutch, German, French, Spanish, and Italian. It predicts the sentiment of the review as a number of stars (between 1 and 5).

This model is intended for direct use as a sentiment analysis model for product reviews in any of the six languages above or for further finetuning on related sentiment analysis tasks.


**tokenizer** = AutoTokenizer.from_pretrained('nlptown/bert-base-multilingual-uncased-sentiment') : This brings the tokenizer





In [ ]:
tokenizer = AutoTokenizer.from_pretrained('nlptown/bert-base-multilingual-uncased-sentiment')

model = AutoModelForSequenceClassification.from_pretrained('nlptown/bert-base-multilingual-uncased-sentiment')

/usr/local/lib/python3.10/dist-packages/huggingface_hub/utils/_token.py:88: UserWarning: 
The secret `HF_TOKEN` does not exist in your Colab secrets.
To authenticate with the Hugging Face Hub, create a token in your settings tab (https://huggingface.co/settings/tokens), set it as secret in your Google Colab and restart your session.
You will be able to reuse this secret in all of your notebooks.
Please note that authentication is recommended but still optional to access public models or datasets.
  warnings.warn(


tokenizer_config.json:   0%|          | 0.00/39.0 [00:00<?, ?B/s]

config.json:   0%|          | 0.00/953 [00:00<?, ?B/s]

vocab.txt:   0%|          | 0.00/872k [00:00<?, ?B/s]

special_tokens_map.json:   0%|          | 0.00/112 [00:00<?, ?B/s]

pytorch_model.bin:   0%|          | 0.00/669M [00:00<?, ?B/s]

# 3. Encode and Calculate Sentiment

This tokenizer.encode will convert the string to numerical value and return the pythorch tensor

In [ ]:
tokens = tokenizer.encode('It was ok but couldve been good. ok', return_tensors='pt')

This will generate the converted the input text into numerical tokens that can be processed by a pre-trained model.

In [ ]:
tokens

tensor([[  101, 10197, 10140, 43060, 10502, 12296, 10598, 10662, 43060,   119,
         24433,   102]])

This numerical token can be decoded or encoded again

In [ ]:
tokens[0]

tensor([  101, 10197, 10140, 43060, 10502, 12296, 10598, 10662, 43060,   119,
        24433,   102])

Lets decode the numerical value

In [ ]:
tokenizer.decode(tokens[0])

'[CLS] it was ok but couldve been good. ok [SEP]'

In [ ]:
# the encoded string of numberical is inside tokens
result = model(tokens)

In [ ]:
result

SequenceClassifierOutput(loss=None, logits=tensor([[ 1.8587,  1.4823,  0.8113, -1.1888, -2.3965]],
       grad_fn=<AddmmBackward0>), hidden_states=None, attentions=None)

logits=tensor([[-2.7768, -1.2353,  1.4419,  1.9804,  0.4584]] : this is the probablity of

In [ ]:
result.logits

tensor([[ 1.8587,  1.4823,  0.8113, -1.1888, -2.3965]],
       grad_fn=<AddmmBackward0>)

In [ ]:
int(torch.argmax(result.logits))+1

3

# Note :
This will return the o/p from 1 to 5 higer the number better the sentiment vice versa

# Output :
    case    score
  1. worst - 1
  2. ok - 3
  5. best - 5


# 4. Collect Reviews

In [ ]:
# r = requests.get('https://www.venuemonk.com/venues/mumbai/hotel-rangsharda-bandra-west')
r = requests.get('https://www.yelp.com/biz/taco-bell-san-francisco-12')

soup = BeautifulSoup(r.text, 'html.parser')
regex = re.compile('.*comment.*')
results = soup.find_all('p', {'class':regex})
reviews = [result.text for result in results]

In [ ]:
soup.find_all('p', {'class' : regex})

[<p class="comment__09f24__D0cxf css-qgunke"><span class="raw__09f24__T4Ezm" lang="en">Amazing Food! One of the best<br/>Great service! I also like the place and ambiance. People here are friendly!</span></p>,
 <p class="comment__09f24__D0cxf css-qgunke"><span class="raw__09f24__T4Ezm" lang="en">worst food ever, contact me for resolving this matter<br/>whatsapp +8801908311196 <br/>I recently visited Taco Bell and had a disappointing experience. The food quality fell short of expectations; it tasted stale and lacked freshness. Additionally, the service was slow, with long wait times despite a minimal crowd. The cleanliness of the restaurant was also questionable, as tables were dirty and the overall environment felt unkempt. I hope they can improve these aspects to offer a better dining experience in the future.</span></p>,
 <p class="comment__09f24__D0cxf css-qgunke"><span class="raw__09f24__T4Ezm" lang="en">If you piss off anyone who works at a Taco Bell, they are definitely going to 

In [ ]:
results[0]

<p class="comment__09f24__D0cxf css-qgunke"><span class="raw__09f24__T4Ezm" lang="en">Amazing Food! One of the best<br/>Great service! I also like the place and ambiance. People here are friendly!</span></p>

In [ ]:
results[0].text

'Amazing Food! One of the bestGreat service! I also like the place and ambiance. People here are friendly!'

In [ ]:
reviews

['Amazing Food! One of the bestGreat service! I also like the place and ambiance. People here are friendly!',
 'worst food ever, contact me for resolving this matterwhatsapp +8801908311196 I recently visited Taco Bell and had a disappointing experience. The food quality fell short of expectations; it tasted stale and lacked freshness. Additionally, the service was slow, with long wait times despite a minimal crowd. The cleanliness of the restaurant was also questionable, as tables were dirty and the overall environment felt unkempt. I hope they can improve these aspects to offer a better dining experience in the future.',
 'If you piss off anyone who works at a Taco Bell, they are definitely going to make sure you get sick after eating there. Avoid this chain at all cost. They are also super greedy and have raised the price of everything while lowering the standard of everything.',
 'So i went to taco bell for a quick little snack,and i ordered a daritos locas taco and i got it and the

# 5. Load Reviews into DataFrame and Score

In [ ]:
import numpy as np
import pandas as pd

In [ ]:
df = pd.DataFrame(np.array(reviews), columns=['review'])

For easy access and traversal we converted this to df with column name as review

In [ ]:
df['review'].iloc[0]

'Amazing Food! One of the bestGreat service! I also like the place and ambiance. People here are friendly!'

In [ ]:
def sentiment_score(review):
    tokens = tokenizer.encode(review, return_tensors='pt')
    result = model(tokens)
    return int(torch.argmax(result.logits))+1

In [ ]:
sentiment_score(df['review'].iloc[4])

1

In [ ]:
df['sentiment'] = df['review'].apply(lambda x: sentiment_score(x[:512]))

In [ ]:
df['review']

0    Amazing Food! One of the bestGreat service! I ...
1    worst food ever, contact me for resolving this...
2    If you piss off anyone who works at a Taco Bel...
3    So i went to taco bell for a quick little snac...
4    Food here was so bad and service was so shitty...
5    It gets you what you need. I love how the Taco...
6    We got there the fucking building was closed w...
7    yummmmmm yyum delicious eat her all the time l...
8    Nobody at a fast food restaurant treats you li...
9    Good service good food I have been using this ...
Name: review, dtype: object

In [ ]:
df['review'].iloc[3]

'So i went to taco bell for a quick little snack,and i ordered a daritos locas taco and i got it and there was sardeins in my taco.It was the worst food i had ever had.'

In [ ]:
df

review  sentiment
0  Amazing Food! One of the bestGreat service! I ...          5
1  worst food ever, contact me for resolving this...          1
2  If you piss off anyone who works at a Taco Bel...          1
3  So i went to taco bell for a quick little snac...          1
4  Food here was so bad and service was so shitty...          1
5  It gets you what you need. I love how the Taco...          4
6  We got there the fucking building was closed w...          1
7  yummmmmm yyum delicious eat her all the time l...          5
8  Nobody at a fast food restaurant treats you li...          5
9  Good service good food I have been using this ...          4

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 2 columns):
 #   Column     Non-Null Count  Dtype 
---  ------     --------------  ----- 
 0   review     10 non-null     object
 1   sentiment  10 non-null     int64 
dtypes: int64(1), object(1)
memory usage: 288.0+ bytes
